### ISSUE TITLE
Denial of Service changes?

### ISSUE THREAD

**Issue by jasongrishkoff** [lmachens/meteor-apm-server#15]
Roughly 9 days ago the MDG rolled out some updates to meteorhacks:kadira.  I'm wondering if these changes need to be integrated?

https://github.com/meteorhacks/kadira/pull/264

**Comment by lmachens** [comment]
The updates are relevant for the meteor package and not for the apm server.
You can use https://github.com/lmachens/kadira if you want, which is a fork of meteorhacks:kadira without jQuery dependency and with the changes of https://github.com/meteorhacks/kadira/pull/264
