### ISSUE TITLE
Excessive disk space usage

### ISSUE THREAD

**Issue by jehartzog** [lmachens/meteor-apm-server#18]
Overall everything is running smoothly now, but the last issue I'm seeing is a constant disk space usage that I can't explain yet.

The `cleanup.js` seems to be removing old data, based on looking at the site, but actual disk space usage continuously rises at something like 500MB per day.

I did a little digging and I was able to find a few things but nothing yet which confirms why:

- The sizes of all the docker images `docker ps -s` are all reasonable, under 700 MB.
- The largest folders on the filesystem are `/var/lib/docker/` at 3.7GB and `/var/lib/mongodb/` at 1.1 GB.

I think the size of mongodb is expected, but the docker folder seems to be the one that is growing.

I've already removed the `console.log` commands, and I've verified using `mup logs` that there isn't excessive logging going on, so I'm not sure what is eating up all the disk space here. I'll follow up if I figure out what's going on.

**Comment by lmachens** [comment]
Take a look at sizes of the docker container logs. `find /var/lib/docker/containers/ -name "*.log" -exec ls -lrtsh {} \; | sort -n -r | head -20`.
I had an issue where mongo created huge log files. You could set the mongo log level or limit docker logs.

**Comment by jehartzog** [comment]
Thanks, that is definitely the issue. I have a 2GB log file in there.

I'll start looking up how to fix this and post the answer once I figure it out. If you happen to know offhand how to do this quickly, that would be appreciated 😆 .

**Comment by jehartzog** [comment]
Got it, to kill the existing log just run `cat /dev/null > /var/lib/docker/containers/CONTAINER_ID/CONTAINER_ID-json.log`.

The mongo log level was already set to the lowest, with no way to lower it further. I looking into setting docker log options, but it seemed difficult to do that given the way MUP automatically sets up and executes the docker containers.

In the end I just created a crontab for sudo to run the cleanup commands every night. Dirty but effective enough.

Disk usage looks steady now, and with keeps 7 days worth of data CPU usage is only sometimes pegging at 100% of a t2.micro unlimited ec2 instance. Stable enough for now :).

**Comment by jasongrishkoff** [comment]
@jehartzog looks like I just ran into this problem as well -- those files got huge and my Kadira stopped logging. Were you able to figure out a clean way to identify the container IDs? Or did you have to `docker ps` and find them before writing your crontab?

Could we not just figure out a way to stop it from writing these logs? I don't see most people logging into their server to access the logs... Or are they a necessary part of the client side?

**Comment by jehartzog** [comment]
I ran the command listed above: `find /var/lib/docker/containers/ -name "*.log" -exec ls -lrtsh {} \; | sort -n -r | head -20`.

I grabbed the container ID's from the two largest log files and added the two commands to empty those files daily to the sudo crontab.

I looked into reducing the actual logging, but I did not find a straightforward way to do it without doing some detailed work into how MUP gets its docker containers up and running. The crontab was the quick and dirty solution.

**Comment by markreid** [comment]
From memory you can specify an `args` array in the `docker` block of your mup.js, like:

```
docker: {
  image: 'whatever/image-name',
  args: [
    '--log-driver json-file',
    '--log-opt max-size=100m',
    '--log-opt max-file=3'
  ]
}
```

This would specify that you want to use JSON for your log format, that your log files shouldn't get larger than 100MB and that you'll rotate through 3 log files.

**Comment by jasongrishkoff** [comment]
My server seems to have completely stopped recording data. Things still running smoothly for you guys?

**Comment by lmachens** [comment]
@jasongrishkoff Still working. Did you check disk usage and logs?

**Comment by ivan046** [comment]
@jasongrishkoff I had that happened twice (in December and in January). Now I've made some changes and if there is no stops next week, I'll share.
