### ISSUE TITLE
Method '__dynamicImport' not found

### ISSUE THREAD

**Issue by jasongrishkoff** [lmachens/meteor-apm-server#19]
Just deployed this to production for the first time and I'm seeing this error come up in the Kadira logs:
```
message: Method '__dynamicImport' not found [404] 
stack:
Error: Method '__dynamicImport' not found [404]
    at Session.method (packages/ddp-server/livedata_server.js:671:18)
    at packages/lmachens_kadira.js:2617:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Session.sessionProto.protocol_handlers.method (packages/lmachens_kadira.js:2616:44)
    at packages/ddp-server/livedata_server.js:559:43
```
I'm running Meteor 1.6.1 -- not sure if that has something to do with it?

**Comment by lmachens** [comment]
I don't think this has something to do with kadira. Do you use [dynamic imports](https://docs.meteor.com/packages/dynamic-import.html) in your app?

**Comment by jasongrishkoff** [comment]
Yes, I do. Okay -- thought maybe it was Kadira given that's the only thing referenced.
