### ISSUE TITLE
Connection successful but nothing displayed

### ISSUE THREAD

**Issue by JanSchuermannn** [lmachens/meteor-apm-server#30]
I deployed the APM on a fresh EC2 instance and everything went through without any issues.
I can access the UI and log in, but after I re-deployed my app with the credentials from the UI, I get 

"Kadira: Successfully connected" but nothing else.

The UI is still displaying the credentials and not loading the data from the app.

Any idea?

**Comment by jehartzog** [comment]
Look at the console/network logs on your Meteor application to see if you're getting the same issues as #14.

**Comment by JanSchuermannn** [comment]
Nothing in the network logs, but changing the nginx config (as explained at the bottom of #14 ) did the trick. Thanks.
