### ISSUE TITLE
Kadira Successfully connected but no data

### ISSUE THREAD

**Issue by funkyremi** [lmachens/meteor-apm-server#33]
I don't get any data on apm server after connecting my application to the server. 
The apm application page still display settings instructions even after I get the message "Kadira: Successfully connected" and  "Kadira: completed instrumenting the app" with the keyid and keysecret.
I don't have a firewall blocking connection.

**Comment by lmachens** [comment]
Do you have any client side errors?

**Comment by funkyremi** [comment]
No client or server side error. Just the "Configure your app" page still displayed and no data available.

**Comment by lmachens** [comment]
Please check if you have the nginx issue described in 2. https://github.com/lmachens/meteor-apm-server#configuration-details
If the port shows 80 this might be the issue.

Did you setup the server with mup?

**Comment by funkyremi** [comment]
Ok that's it, the MUP hooks may be failing because I see port 80. Yes the server has been setup with MUP. What should I try to resolve this issue?

**Comment by lmachens** [comment]
Take a look at https://github.com/lmachens/meteor-apm-server/issues/14#issuecomment-360994087

Looks like the mup hook didn't work for you https://github.com/lmachens/meteor-apm-server/blob/master/mup-placeholder.js#L57

@jehartzog did you notice issues with your solution?

**Comment by jehartzog** [comment]
It works fine for me, but I freely admin that fix is hacky and probably won't work in all cases. For example, it relies on the apm-engine app being listed first in the proxy file, which may not always happen.

If it doesn't work @funkyremi you'll need to manually edit the port in the `/etc/nginx/conf.d/default.conf` file in the docker container.

**Comment by funkyremi** [comment]
Thank you it's working after manually editing the default.conf file and restarting the service.

**Comment by Ehrs** [comment]
I am also having trouble with this `default.conf` file. The "solution" with manually editing `default.conf` is somehow automatically reverted after a while (around 8 hours). How can I find what is causing this? I manually edit the file and then run `npx mup deploy` to make it work for a while. I also tried `docker restart mup-nginx-proxy` at my apm server but that would instantly revert my changes and use port 80 again.

**Comment by jehartzog** [comment]
If the server restarts then the proxy settings are reset, same with restarting the proxy. Sounds like your server is probably restarting every 8 hours for some reason.

**Comment by Ehrs** [comment]
I have an uptime that says otherwise... 

Am I missing some detail in how docker container works? I make manual changes outside the container then copying it to a `default2.conf` using

    docker cp default.conf mup-nginx-proxy:/etc/nginx/conf.d/default.conf2
followed by

    docker exec -t mup-nginx-proxy cp /etc/nginx/conf.d/default.conf2 /etc/nginx/conf.d/default.conf

**Comment by jehartzog** [comment]
I don't see anything wrong with how you're doing it, but I just directly edited using `vi` or `vim`, which I had to install in the container.

Other things which will reset the proxy config are running a mup deploy again, even if you server is up and running, so if you are pushing code updates that could also be causing the reset.

**Comment by Ehrs** [comment]
Made a lazy attempt to install `vim` in the container but it didn't work first try so I did it like this. :)

After manually editing the file, should I just restart the container `mup-nginx-proxy`? That makes the most sense to me but it didn't really work.

**Comment by jehartzog** [comment]
Restarting the container will end up with your config changes being reset. Instead just tell the container to reload nginx:

```
docker exec mup-nginx-proxy nginx -s reload
```

A longer discussion about all this stuff is [here](https://github.com/lmachens/meteor-apm-server/issues/14#issuecomment-360992936).

**Comment by lmachens** [comment]
I think we need a better solution here. If the nginx container restarts and overwrites the config, this error will happen again.
Maybe we can use the mup [advanced proxy settings](http://meteor-up.com/docs.html#advanced-configuration)?
```
// This config can add additional upstream and server blocks if needed.
nginxConfig: './path/to/config',
```
Or use env vars for nginx proxy to change the [nginx config](https://github.com/jwilder/nginx-proxy/blob/ccbbbeb928a560353f73d2e6661abe03c3a28831/nginx.tmpl)?
```
// Environment variables for nginx proxy
env: {
 DEFAULT_HOST: 'foo.bar.com'
}
```

I think the issue is that we expose different ports for different domains. 
There is a discussion on https://github.com/jwilder/nginx-proxy/issues/59.

Ideas/PRs are welcome :).

**Comment by jehartzog** [comment]
I spent a decent amount of time looking into this, and there was not a simple solution, at least many months ago. That was before MUP released it's nginx config features, so it may be doable now. I'll take another look into it, no promises though :D.

**Comment by vparpoil** [comment]
Hello there, 
I just installed successfully the APM, but got this issue. 
I fixed manually using these steps : 
- `docker ps` to list containers
- `docker exec -ti CONTAINER_ID /bin/bash` to enter the docker  container named `mup-nginx-proxy`
- manually edit `/etc/nginx/conf.d/default.conf` to change port 80 by port 11011 for the apm-engine upstream (I also had to install vi on the docker)
- `nginx -t` to test config, then `service nginx reload`
I am pretty sure this fix won't stay after a new deployment using mup...

**Comment by lmachens** [comment]
@vparpoil see discussion in https://github.com/lmachens/meteor-apm-server/issues/14
