### ISSUE TITLE
Error: 'very strange! - no entries found'

### ISSUE THREAD

**Issue by gaetandezeiraud** [lmachens/meteor-apm-server#37]
Hi, 
I setup mongoDB in my system manually and I use this Docker command:
```
sudo docker run -d --name meteor-apm-server --net="host" \
  -p 4000:80 \
  -p 7007:7007 \
  -p 11011:11011 \
  -e PORT=80 \
  -e MONGO_URL=mongodb://localhost:27017/meteor \
  -e MONGO_OPLOG_URL=mongodb://localhost:27017/local \
  -e ROOT_URL=http://url.domain.com \
  strictlyskyler/meteor-apm-server:1.1.0
```

Kadira-UI run and I changed my password. On my Meteor application I have `I20180612-20:23:50.341(2)? Kadira: completed instrumenting the app` and `I20180612-20:23:50.362(2)? Kadira: Successfully connected`. But, the dashboard is always at the **Configure Your App** page. 

And with a Docker logs I have this message:
```
in the root directory of your application.
Kadira Alertsman started
Fetchman started on port: 7007
starting apm-engine on port 11011
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
very strange! - no entries found
   cleaned up 0 in 7 ms
```

Any ideas ? Thanks.

**Comment by lmachens** [comment]
Hey,

it might be related to https://github.com/lmachens/meteor-apm-server/issues/33#issuecomment-384273307.
Please verify that nginx has the correct port.

**Comment by gaetandezeiraud** [comment]
I don't use MUP (so mup-nginx-proxy) or nginx, just meteor-apm-server with docker and MongoDB on host. 
So the nginx conf doesn't exist 
```
sudo docker exec -it meteor-apm-server /bin/bash
root@server:/apm/bundle/programs/server# cat /etc/nginx/conf.d/default.conf
cat: /etc/nginx/conf.d/default.conf: No such file or directory
```

I will manage, thank you for your help.

**Comment by lmachens** [comment]
`very strange! - no entries found` is normal until you connected a client to the APM server.

**Comment by gaetandezeiraud** [comment]
I fix the problem, i directly use ip address of my server with the port 11011 and it work correctly without nginx. 

Thanks for your time and your job for this project!

**Comment by lmachens** [comment]
👍
