### ISSUE TITLE
UI crashes after a while

### ISSUE THREAD

**Issue by sandeepjain** [lmachens/meteor-apm-server#40]
After sometime of `meteor-apm-server` deployment, the UI crashes with 401 error in frontend while engine keeps on collecting the data.

Logs shows something like below:

```
blocked due missing appId:  /
blocked due missing appId:  /
blocked due missing appId:  /
blocked due missing appId:  /
blocked due missing appId:  /
blocked due missing appId:  /
blocked due missing appId:  /
blocked due missing appId:  /kadira-logo-light.png
blocked due missing appId:  /kadira-logo-light.png
blocked due missing appId:  /kadira-logo-light.png
blocked due missing appId:  /
blocked due missing appId:  /
```

I tried accessing static resource as well, but same issue even those could not be loaded.

If anybody here, have insight into this, please help.

**Comment by lmachens** [comment]
Do you have to restart the server when this happens? I would take a look at cpu/memory usage when this happens.

**Comment by sandeepjain** [comment]
No event after restart it doesn't work.

Actually, apm engine still keeps on collecting the data.

Now after posting the issue, I was re-checking all the configuration. It seems the script I was running manually to reconfigure the port 80 to 11011 had a flaw in it.

I was manually running this on my server, as `post.meteor.init` hook doesn't seem to be working.

```
docker exec mup-nginx-proxy sed -i 's/server x.x.x.x:80/server x.x.x.x:11011/g' /etc/nginx/conf.d/default.conf && docker exec mup-nginx-proxy nginx -s reload
```

But I failed to make sure that only configuration for apm-engine should be changed. Dumb of me.

Apologies for trouble.

But we need to find a way to make this hook work seamlessly. I will look into it and update if I find any solution to it.

Thanks, @lmachens
