### ISSUE TITLE
Email alerts are overly active

### ISSUE THREAD

**Issue by vbgm** [lmachens/meteor-apm-server#43]
After setting up the MAIL_URL and trying to setup an alert I kept getting the same alert multiple times (60+ emails), even when setting it to be sent once.

**Comment by lmachens** [comment]
I never setup mailing (Slack alerts should work fine).
Do you get multiple alerts at the same time or are there some minutes between?
You can check console.log which should show you if a send is triggered or cleared:

https://github.com/lmachens/meteor-apm-server/blob/e02f924bd27381b773798ff18824d93cd1a2532f/server/alertsman/server/index.js#L62-L78

**Comment by vbgm** [comment]
Unfortunately I do not use Slack. The alerts are being sent every 10 seconds repeatedly. In the log it kept on showing "sendTriggered" and seem never "sendCleared".

**Comment by afrokick** [comment]
Me too, but i use slack. Every 10 seconds. I'll try to find steps to reproduce.

**Comment by markreid** [comment]
I've also had this one. Alert  triggered and then flooded a slack channel until I removed it. Didn't really have time to investigate it though, just had to leave it off.

**Comment by afrokick** [comment]
@vblagomir @markreid do you use oplog? I dont. I think AlertsManager cannot receive updates from DB without Oplog.

**Comment by vbgm** [comment]
I have initially wrote 'Yes', but then thought that depending on how the whole setup has been done, oplog might have been NOT enabled. This might be the issue indeed.

**Comment by afrokick** [comment]
> Yes.

Could you please try to run monitoring with DEBUG env var?
`DEBUG=alertsman:altersStore meteor`

You should see the message  like this
`Mon, 15 Jul 2019 14:08:20 GMT alertsman:altersStore reset and load 1 alerts` in console after run.

**Comment by vbgm** [comment]
I have edited my 'Yes'. And because of workload the earliest time I could check this would be in couple of months.

**Comment by afrokick** [comment]
> I have edited my 'Yes'. And because of workload the earliest time I could check this would be in couple of months.

Ok, it is the reason of issue. Without Oplog it doesn't work.

@lmachens did you start to work on item 'Direct db access of alertsman' from ToDo ? Maybe I can help with it

**Comment by afrokick** [comment]
@lmachens Done https://github.com/afrokick/meteor-apm-server/pull/1

**Comment by vbgm** [comment]
> Ok, it is the reason of issue. Without Oplog it doesn't work.

I hope this is the reason, if after checking it appears not the case, I will reopen it then. Thank you for your effort investigating!
