### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by lmachens** [lmachens/meteor-apm-server#47]
Hi, I am looking for maintainers for this project, because I don't use Meteor in my projects anymore.
If you want to become a maintainer, please answer to this thread.
Thanks!

**Comment by jehartzog** [comment]
I think I'm already maintainer, but to be clear I still use this in production and will continue to do so for a while. If I know you're off it completely I'll be more active in fixing anything that pops up. 

Thanks for asking for maintainers, it's awesome you put all this together and are making sure it gets handed off.

**Comment by markreid** [comment]
👋 we use this in production at my work. we're pretty flat out most of the time but would be happy to try and jump in to resolve issues when needed. i haven't had much time to look at how it works under the hood to be honest but for the most part it seems to just tick along...

**Comment by lmachens** [comment]
thx guys! you should be invited as a collaborator now. 
I invited you to collaborate in https://github.com/lmachens/kadira too (feel free to accept).

**Comment by justbill2020** [comment]
Please add me as well. I will be using in a new project thank you

**Comment by lmachens** [comment]
@justbill2020 done

**Comment by obonyojimmy** [comment]
Hi, @lmachens  kindly add me too, very interested on the project after trying it out.
